### ISSUE TITLE
Undeclared requirement: matplotlib

### ISSUE THREAD

**Issue by mdickinson** [mmaelicke/scikit-gstat#10]
A very minor bug: `matplotlib` appears to be a hard requirement of the package, but isn't listed in the `requirements.txt` file.

```
(testing-gstat)bash-3.2$ python
Enthought Deployment Manager -- https://www.enthought.com
Python 3.6.0 |Enthought, Inc. (x86_64)| (default, Mar  3 2017, 03:26:01) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy as np
>>> import skgstat as skg
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/mdickinson/.edm/envs/testing-gstat/lib/python3.6/site-packages/skgstat/__init__.py", line 3, in <module>
    from .Variogram import Variogram
  File "/Users/mdickinson/.edm/envs/testing-gstat/lib/python3.6/site-packages/skgstat/Variogram.py", line 12, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
>>> ^D 
```

**Comment by mmaelicke** [comment]
Thanks for reporting!   
I added matplotlib to requirements.txt in the latest commit (along with another missing requirement).
